---

- hosts: all
  become: true

  # vars:
  #   - allowed_ports:
  #     - 80
  #     - 443

  roles:
    - utils
    # - security

  tasks:
    - name: Install MySQL
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - mariadb-server
        - php-mysql
        - MySQL-python

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - include_vars: "secrets.yaml"
    - name: Add MySQL user
      mysql_user:
        name: "{{ owncloud_mysql_username }}"
        password: "{{ owncloud_mysql_password }}"
        priv: '{{ owncloud_mysql_dbname}}.*:ALL'
        state: present

    - name: Install Owncloud
      yum:
        name: owncloud
        state: latest

    - name: Allow remote access to owncloud
      file:
        src: /etc/httpd/conf.d/owncloud-access.conf.avail
        dest: /etc/httpd/conf.d/z-owncloud-access.conf
        state: link

    - name: Start Apache Web Server
      service:
        name: httpd
        state: started
        enabled: yes
