# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for creating a instance using Vultr as a provider and bootstrapping with Ansible
Vagrant.configure(2) do |config|

    config.vm.define "local" do |local|
        local.vm.box = "centos/7"
        local.vm.hostname = "cloud.patcave.local"
        local.vm.network "forwarded_port", guest: 80, host: 8080

        local.vm.provider "virtualbox" do |virtualbox|
            virtualbox.memory = 2048
        end
        local.vm.provision :ansible do |ansible|
            ansible.playbook = 'playbook.yaml'
            ansible.ask_vault_pass = true
        end
    end

    config.vm.define "cloud" do |cloud|
        cloud.vm.hostname = "cloud.patcave.me"
        cloud.vm.provider :vultr do |vultr, override|
            override.vm.hostname = 'cloud.patcave.me'
            override.ssh.private_key_path = '~/.ssh/zerus'
            override.vm.box = 'vultr'
            override.vm.box_url = 'https://github.com/p0deje/vagrant-vultr/raw/master/box/vultr.box'

            # API token: https://my.vultr.com/settings/#settingsapi
            vultr.token = 'CHIBLZHCPO4AU34A3HY65WQASHFTWH'

            # Regions:
            #   curl https://api.vultr.com/v1/regions/list
            #   - New Jersey
            #   - Chicago
            #   - Dallas
            #   - Seattle
            #   - Los Angeles
            #   - Atlanta
            vultr.region = 'New Jersey'

            # Plans:
            #   curl https://api.vultr.com/v1/plans/list
            #   Storage:
            #   - 512 MB RAM,125 GB SATA,1.00 TB BW
            #   - 1024 MB RAM,250 GB SATA,2.00 TB BW
            #   - 2048 MB RAM,500 GB SATA,3.00 TB BW
            #   - 4096 MB RAM,1000 GB SATA,5.00 TB BW
            #   Compute:
            #   - 768 MB RAM,15 GB SSD,1.00 TB BW
            #   - 1024 MB RAM,20 GB SSD,2.00 TB BW
            #   - 2048 MB RAM,45 GB SSD,3.00 TB BW
            #   - 4096 MB RAM,90 GB SSD,4.00 TB BW
            vultr.plan = '512 MB RAM,125 GB SATA,1.00 TB BW'

            # Operating Systems:
            #   curl https://api.vultr.com/v1/os/list
            #   - CentOS 6 x64
            #   - Ubuntu 12.04 x64
            #   - Ubuntu 14.04 x64
            #   - Debian 7 x64 (wheezy)
            vultr.os = 'CentOS 7 x64'

        end

        cloud.vm.provision :ansible do |ansible|
            ansible.playbook = 'playbook.yaml'
        end
    end
end
