---

- name: Install EPEL
  yum:
    name: epel-release
    state: latest
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Install Utility Packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - htop
    - vim
    - psmisc
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
